services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.development.local
        required: false

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.development.local
        required: false
    ports:
      - ${PORT}:${PORT}

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    volumes:
      - metabase-data:/metabase-data

volumes:
  postgres:
  metabase-data:
