services:
  server:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.development.local
        required: false
    ports:
      - ${PORT}:${PORT}

volumes:
  postgres:
