export enum ALERT_CODES {
  FURNACE_OVERHEAT = 'FURNACE_OVERHEAT',
  CRITICAL_LOW_EFFICIENCY = 'CRITICAL_LOW_EFFICIENCY',
  CRITICAL_FUEL_DEPLETION = 'CRITICAL_FUEL_DEPLETION',
  CRITICAL_AIR_LEAKAGE = 'CRITICAL_AIR_LEAKAGE',
  CRITICAL_CONVECTIVE_TEMPERATURE = 'CRITICAL_CONVECTIVE_TEMPERATURE',
  CRITICAL_ECONOMIZER_TEMPERATURE = 'CRITICAL_ECONOMIZER_TEMPERATURE',
  CRITICAL_FOULING = 'CRITICAL_FOULING',
  CRITICAL_EXCESS_AIR = 'CRITICAL_EXCESS_AIR',
  CRITICAL_LOAD = 'CRITICAL_LOAD',
  SOLVER_IMBALANCE = 'SOLVER_IMBALANCE',
}
